### ISSUE TITLE
Asset Updater: Support for the Light (Personal) Skin

### ISSUE THREAD

**Issue by michidk** [kode80/UnityTools#3]
Currently the asset updater looks a little bit weird when using it with the unity personal skin.
Also the text is hard to read.
![](http://i.imgur.com/VUuHxZp.png)

**Comment by kode80** [comment]
I noticed that in your screenshot and figured that was the case. No problem, I'll add a check for the personal version and use a more appropriate gradient.

**Comment by kode80** [comment]
This is now implemented in the develop branch so will be in the next official release.
